name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  version: ${{ github.sha }}
  dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
  dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
  server_host: ${{ secrets.SERVER_HOST }}
  server_username: ${{ secrets.SERVER_USERNAME }}
  server_password: ${{ secrets.SERVER_PASSWORD }}
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:
        cd eureka-server;
        .\mvnw clean -DskipTests=true package;
        docker build . --file Dockerfile --tag phongvanngo/dochero-service-registry:latest;
        docker tag phongvanngo/dochero-service-registry:latest phongvanngo/dochero-service-registry:$version;
        docker images;
        docker login --username=${dockerhub_username} --password=${dockerhub_password};
        docker push phongvanngo/dochero-service-registry:$version;
        docker push phongvanngo/dochero-service-registry:latest;
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: cd /docker-compose-list/dochero/;sudo git pull;sudo docker-compose pull;sudo docker-compose up -d service-registry;
